config/routes.rb
Rails.application.routes.draw do
  get "/", to: "homepage#home", as: "root"
  resources :excategories
  resources :expenses
  resources :incategories
  resources :incomes
  resources :statistics
  resources :homepage
  resources :instats
  mount ReportsKit::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/incategory.rb
class Incategory < ApplicationRecord
  has_many :incomes
  validates :name,length: { minimum: 2,maximum: 40}, presence: true
  validates :desc,length: {maximum: 150}, presence: true
end

app/controllers/incategories_controller.rb
class IncategoriesController < ApplicationController
  before_action :set_incategory, only: [:show, :edit, :update, :destroy]

  # GET /incategories
  # GET /incategories.json
  def index
    @incategories = Incategory.all
  end

  # GET /incategories/1
  # GET /incategories/1.json
  def show
  end

  # GET /incategories/new
  def new
    @incategory = Incategory.new
  end

  # GET /incategories/1/edit
  def edit
  end

  # POST /incategories
  # POST /incategories.json
  def create
    @incategory = Incategory.new(incategory_params)

    respond_to do |format|
      if @incategory.save
        format.html { redirect_to @incategory, notice: 'Incategory was successfully created.' }
        format.json { render :show, status: :created, location: @incategory }
      else
        format.html { render :new }
        format.json { render json: @incategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incategories/1
  # PATCH/PUT /incategories/1.json
  def update
    respond_to do |format|
      if @incategory.update(incategory_params)
        format.html { redirect_to @incategory, notice: 'Incategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @incategory }
      else
        format.html { render :edit }
        format.json { render json: @incategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incategories/1
  # DELETE /incategories/1.json
  def destroy
    @incategory.destroy
    respond_to do |format|
      format.html { redirect_to incategories_url, notice: 'Incategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incategory
      @incategory = Incategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incategory_params
      params.require(:incategory).permit(:name, :desc)
    end
end

app/helpers/incategories_helper.rb
module IncategoriesHelper
end

app/views/incategories/_form.html.erb
<%= form_with(model: incategory, local: true) do |form| %>
  <% if @incategory.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(@incategory.errors.count, "error") %>
              prohibited this category from being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% @incategory.errors.full_messages.each do |msg|%>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-xs-12">
      <%= form_for(@incategory, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="col-sm-6">
            <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true %>
          </div>
        </div>
        <div class="control-label col-sm-2">
          <%= f.label :desc %>
        </div>
        <div class="form-group">
          <div class="col-sm-6">
            <%= f.text_area :desc, rows: 10, class: "form-control", placeholder: "Description" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-large' %>
          </div>
        </div><% end %>
    </div>
  </div>
<% end %>

app/views/incategories/edit.html.erb
<h1>Editing Incategory</h1>

<%= render 'form', incategory: @incategory %>

<%= link_to 'Show', @incategory,class: "btn btn-xs btn-primary" %> |
<%= link_to 'Back', incategories_path , class: "btn btn-xs btn-success"%>

app/views/incategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Income categories</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incategories.each do |incategory| %>
      <tr>
        <td><%= incategory.name %></td>
        <td><%= link_to 'Show', incategory ,class: "btn btn-xs  btn-info"%></td>
        <td><%= link_to 'Edit', edit_incategory_path(incategory),class: "btn btn-xs btn-primary"  %></td>
        <td><%= link_to 'Destroy', incategory, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incategory', new_incategory_path,class: "btn btn-xs btn-primary"  %>
<%= link_to "Back", root_path , class: "btn btn-xs btn-success" %>

app/views/incategories/new.html.erb
<h1>New Incategory</h1>

<%= render 'form', incategory: @incategory %>

<%= link_to 'Back', incategories_path , class: "btn btn-xs btn-success",class: "btn btn-xs btn-primary" %>

app/views/incategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @incategory.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @incategory.desc %>
</p>

<%= link_to 'Edit', edit_incategory_path(@incategory),class: "btn btn-xs btn-primary" %> |
<%= link_to 'Back', incategories_path , class: "btn btn-xs btn-success" %>