config/routes.rb
Rails.application.routes.draw do
  get "/", to: "homepage#home", as: "root"
  resources :excategories
  resources :expenses
  resources :incategories
  resources :incomes
  resources :statistics
  resources :homepage
  resources :instats
  mount ReportsKit::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :incategory
  validates :price, numericality: {greater_than: 0 }, presence: true
  validates :name,length: { minimum: 2,maximum: 40}, presence: true
  validates :desc,length: {maximum: 150}, presence: true
  validates :incategory_id, presence: true
  accepts_nested_attributes_for :incategory
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.order('updated_at DESC')
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)
    @income.incategory_id = params[:incategory_id]
    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    @income.incategory_id = params[:incategory_id]
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:name, :price, :desc, :create_date, :upd_date, :incategory_id)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<% if @income.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@income.errors.count, "error") %>
            prohibited this income from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% @income.errors.full_messages.each do |msg|%>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@income, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :desc %>
        </div>
        <div class="col-sm-6">
          <%= f.text_area :desc, rows: 10, class: "form-control", placeholder: "Description" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :price%>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :price, class: "form-control", placeholder: "Price", autofocus: true %>
        </div>
      </div>
      <div class="CatMarg">
        <div >
          <% inarray = Incategory.all.map { |incategory| [incategory.name, incategory.id] }  %>
          <%= select_tag(:incategory_id, options_for_select(inarray)) %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-large' %>
        </div>

      </div><% end %>
  </div>
</div>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Show', @income, class: "btn btn-xs btn-success"  %> |
<%= link_to 'Back', incomes_path ,class: "btn btn-xs btn-primary"%>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Incomes</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.name %></td>
        <td><%= income.price %></td>
        <td><%= income.incategory.name if income.incategory_id? %></td>
        <td><%= income.updated_at.strftime("%B %d %Y") %></td>
        <td><%= link_to 'Show', income ,class: "btn btn-xs  btn-info"%></td>
        <td><%= link_to 'Edit', edit_income_path(income),class: "btn btn-xs btn-primary" %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income', new_income_path ,class: "btn btn-xs btn-primary" %>
<%= link_to "Back", root_path , class: "btn btn-xs btn-success" %>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Back', incomes_path , class: "btn btn-xs btn-success" %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @income.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @income.price %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @income.desc %>
</p>

<p>
  <strong>Create date:</strong>
  <%= @income.create_date %>
</p>

<p>
  <strong>Upd date:</strong>
  <%= @income.upd_date %>
</p>

<p>
  <strong>Incategory:</strong>
  <%= @income.incategory.name if @income.incategory_id?%>
</p>

<%= link_to 'Edit', edit_income_path(@income) , class: "btn btn-xs btn-success" %> |
<%= link_to 'Back', incomes_path ,class: "btn btn-xs btn-primary" %>