config/routes.rb
Rails.application.routes.draw do
  get "/", to: "homepage#home", as: "root"
  resources :excategories
  resources :expenses
  resources :incategories
  resources :incomes
  resources :statistics
  resources :homepage
  resources :instats
  mount ReportsKit::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/excategory.rb
class Excategory < ApplicationRecord
  has_many :expenses
  validates :name,length: { minimum: 2,maximum: 40}, presence: true
  validates :desc,length: {maximum: 150}, presence: true
end

app/controllers/excategories_controller.rb
class ExcategoriesController < ApplicationController
  before_action :set_excategory, only: [:show, :edit, :update, :destroy]

  # GET /excategories
  # GET /excategories.json
  def index
    @excategories = Excategory.all
  end

  # GET /excategories/1
  # GET /excategories/1.json
  def show
  end

  # GET /excategories/new
  def new
    @excategory = Excategory.new
  end

  # GET /excategories/1/edit
  def edit
  end

  # POST /excategories
  # POST /excategories.json
  def create
    @excategory = Excategory.new(excategory_params)

    respond_to do |format|
      if @excategory.save
        format.html { redirect_to @excategory, notice: 'Excategory was successfully created.' }
        format.json { render :show, status: :created, location: @excategory }
      else
        format.html { render :new }
        format.json { render json: @excategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /excategories/1
  # PATCH/PUT /excategories/1.json
  def update
    respond_to do |format|
      if @excategory.update(excategory_params)
        format.html { redirect_to @excategory, notice: 'Excategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @excategory }
      else
        format.html { render :edit }
        format.json { render json: @excategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /excategories/1
  # DELETE /excategories/1.json
  def destroy
    @excategory.destroy
    respond_to do |format|
      format.html { redirect_to excategories_url, notice: 'Excategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excategory
      @excategory = Excategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def excategory_params
      params.require(:excategory).permit(:name, :desc)
    end
end

app/helpers/excategories_helper.rb
module ExcategoriesHelper
end

app/views/excategories/_form.html.erb
<%= form_with(model: excategory, local: true) do |form| %>
  <% if @excategory.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(@excategory.errors.count, "error") %>
              prohibited this category from being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% @excategory.errors.full_messages.each do |msg|%>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-12">
      <%= form_for(@excategory, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="col-sm-6">
            <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :desc %>
          </div>
          <div class="col-sm-6">
            <%= f.text_area :desc, rows: 10, class: "form-control", placeholder: "Description" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-large' %>
          </div>
        </div><% end %>
    </div>
  </div>
<% end %>

app/views/excategories/edit.html.erb
<h1>Editing Excategory</h1>

<%= render 'form', excategory: @excategory %>

<%= link_to 'Show', @excategory ,class: "btn btn-xs  btn-info"%> |
<%= link_to 'Back', excategories_path ,class: "btn btn-xs btn-primary"%>

app/views/excategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Excategories</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @excategories.each do |excategory| %>
      <tr>
        <td><%= excategory.name %></td>
        <td><%= link_to 'Show', excategory ,class: "btn btn-xs  btn-info"%></td>
        <td><%= link_to 'Edit', edit_excategory_path(excategory) ,class: "btn btn-xs btn-primary"%></td>
        <td><%= link_to 'Destroy', excategory, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-xs btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Excategory', new_excategory_path ,class: "btn btn-xs btn-primary"%>
<%= link_to "Back", root_path , class: "btn btn-xs btn-success"%>

app/views/excategories/new.html.erb
<h1>New Excategory</h1>

<%= render 'form', excategory: @excategory %>

<%= link_to 'Back', excategories_path , class: "btn btn-xs btn-success" %>

app/views/excategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @excategory.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @excategory.desc %>
</p>

<%= link_to 'Edit', edit_excategory_path(@excategory), class: "btn btn-xs btn-success"  %> |
<%= link_to 'Back', excategories_path ,class: "btn btn-xs btn-primary"%>