config/routes.rb
Rails.application.routes.draw do
  get "/", to: "homepage#home", as: "root"
  resources :excategories
  resources :expenses
  resources :incategories
  resources :incomes
  resources :statistics
  resources :homepage
  resources :instats
  mount ReportsKit::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.order('updated_at DESC')
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
      @expense = Expense.new


  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)
    @expense.excategory_id = params[:excategory_id]
    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    @expense.excategory_id = params[:excategory_id]
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:name, :price, :desc, :create_date, :upd_date, :excategory_id)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<% if @expense.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@expense.errors.count, "error") %>
            prohibited this expense from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% @expense.errors.full_messages.each do |msg|%>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
 <div class="row">
  <div class="col-xs-12">
    <%= form_for(@expense, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :desc %>
        </div>
        <div class="col-sm-6">
          <%= f.text_area :desc, rows: 10, class: "form-control", placeholder: "Description" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :price%>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :price, class: "form-control", placeholder: "Price", autofocus: true %>
        </div>
      </div>
      <div class="CatMarg">
      <div >
        <% exarray = Excategory.all.map { |excategory| [excategory.name, excategory.id] }  %>
        <%= select_tag(:excategory_id, options_for_select(exarray)) %>
      </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-large' %>
        </div>

      </div><% end %>
  </div>
</div>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense ,class: "btn btn-xs btn-primary" %> |
<%= link_to 'Back', expenses_path , class: "btn btn-xs btn-success" %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expenses</h1>

<table>
  <thead>
  <table class="table table-bordered">
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.name%></td>
        <td><%= expense.price %></td>
        <td><%= expense.excategory.name if expense.excategory_id? %></td>
        <td><%= expense.updated_at.strftime("%B %d %Y") %></td>
        <td><%= link_to 'Show', expense,class: "btn btn-xs  btn-info" %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense),class: "btn btn-xs btn-primary" %> </td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


  <%= link_to "New Expense", new_expense_path, class: "btn btn-xs btn-primary" %> |
<%= link_to 'Back', root_path, class: "btn btn-xs btn-success" %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path , class: "btn btn-xs btn-success"%>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @expense.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @expense.price %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @expense.desc %>
</p>

<p>
  <strong>Create date:</strong>
  <%= @expense.create_date %>
</p>

<p>
  <strong>Upd date:</strong>
  <%= @expense.upd_date %>
</p>

<p>
  <strong>Excategory:</strong>
  <%= @expense.excategory.name if @expense.excategory_id?%>
</p>

<%= link_to 'Edit', edit_expense_path(@expense),class: "btn btn-xs btn-primary" %> |
<%= link_to 'Back', expenses_path , class: "btn btn-xs btn-success"%>